### ISSUE TITLE
Failed to load the wikilink package

### ISSUE THREAD

**Issue by mprimi** [Zettelkasten-Method/atom-wikilink#17]
Hello, I tried to install and got an error. Reporting in case you want to investigate.

Let me know if there's any more data I can provide.

1. Open atom
2. Install the plugin

**Atom**: 1.56.0 x64
**Electron**: 9.4.4
**OS**: macOS 11.2.3
**Thrown From**: [wikilink](https://github.com/Zettelkasten-Method/atom-wikilink) package 0.16.0

### Stack Trace

Failed to load the wikilink package

```
At Unexpected token 'export'

/Users/.../.atom/packages/wikilink/node_modules/escape-string-regexp/index.js:1
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { export default function escapeStringRegexp(string) {
                                                                                                                                                           ^^^^^^

SyntaxError: Unexpected token 'export'
    at new Script (vm.js:84:7)
    at NativeCompileCache.runInThisContext (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:148760)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149614)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149153)
    at /packages/wikilink/lib/wikilink.coffee:4:22)
    at /packages/wikilink/lib/wikilink.coffee:1:1)
    at /packages/wikilink/lib/wikilink.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149837)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:756275)
    at requireModule (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1126113)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3379815)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3366355
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3365155)
    at Package.load (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3365928)
    at PackageManager.loadAvailablePackage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:383596)
    at PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:382324)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:384896)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:911030
    at r (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:905636)
    at n (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1125436)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1125590
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1124192)
    at Socket.emit (events.js:228:7)
    at Pipe.<anonymous> (net.js:664:12)
```

### Commands

```
```

### Non-Core Packages

```
document-outline 2.1.2 
file-icons 2.1.47 
sort-lines 0.19.0 
Sublime-Style-Column-Selection 1.7.5 
wikilink 0.16.0 
```

**Comment by theshoals** [comment]
Thanks for the bug report.

Proposed fix: https://github.com/Zettelkasten-Method/atom-wikilink/pull/18
